language: node_js
node_js:
- '12'
before_install: true
install:
- npm install
before_script: true
script:
- "./node_modules/.bin/jshint ./src/"
- "./node_modules/.bin/retire"
- if [ "$TRAVIS_BRANCH" = "master" ]; then "./node_modules/.bin/twly"; fi
after_script: true
deploy:
  provider: heroku
  api_key:
    secure: VQWIX+1OEXpwl4pzQ2l6wFDbsdAgTbOIGMvLIi1dyby3j4tg+Q6mVnZehjwiPYqFyVHZSiKFbHRyGfPNV++AQCDc3rB1Jla7+UnDIkZJJYTJh2ub4HPxCczy7XUMmjCP8Rok+JN0ur4//rhIvDl6epIdZVX7VPHeENV7UCe4zbPkX30Tr42OOmfe4l9rhy/RYosHSYUHFnbWhiuVp0fvv/f2/LEG0epEm9Xfik6D2+hCdYpA2zoWoaclooTPIayQpSxSJ5GFnz0Zw0g6HMc6FuM+L5TplYl0xPauYMB2AVS4Rs57UWwBiVo5RnIdxnaEvNRQ9T6OEHPlVQgwyWSjMyR7bj+fw6uGwgwEDGZ8eIkauzTJp4bGo0yLoPMmvkN/ZIe+MyNIeDfB7Rcd6/pFfG11XSRDy/HBKYv4I4cqhHkIc3Hj7M9+mmoNDGSqOGrS7V7GJhflsug0kCTzSHSX1Wp1KILpQQnjDADAbzTfJMo928MZJNBDQrr5pIR/5fPQKeJ9+innCpSY+5M4KBenFYb5AomY4SZEZkBvHm4JWBx/eEnXtHiNFTcZ7KvWYcZ+py4wU7L83jwhmqjqivp2RxxuJSf+1Df9gOPJ/UZcUrM9zfP59Q7IVcJg3AOTD/DeMVVHD53Uu+3oHBsvBicijkZU7AWz6dz9f8INtF1dq08=
  app: evaluationipssi
  on:
    branch: dev
    repo: Abdelkader7/IPSSI_Evaluation
